//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortaleFornitori.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documento()
        {
            this.Download = new HashSet<Download>();
        }
    
        public int IdDocumento { get; set; }
        public string Descrizione { get; set; }
        public System.DateTime DataCreazione { get; set; }
        public string NomeFile { get; set; }
        public byte[] Contenuto { get; set; }
        public int IdFornitore { get; set; }
        public string ContentType { get; set; }
        public bool Attivo { get; set; }
    
        public virtual Fornitore Fornitori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Download> Download { get; set; }
    }
}
