//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortaleFornitori.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Download
    {
        public int IdFornitore { get; set; }
        public int IdDocumento { get; set; }
        public System.DateTime DataDownload { get; set; }
        public int IdDownload { get; set; }
    
        public virtual Documento Documenti { get; set; }
        public virtual Fornitore Fornitori { get; set; }
    }
}
