//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortaleFornitori.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortaleFornitoriDbContext : DbContext
    {
        public PortaleFornitoriDbContext()
            : base("name=PortaleFornitoriDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Documento> Documenti { get; set; }
        public virtual DbSet<Fornitore> Fornitori { get; set; }
        public virtual DbSet<Ruolo> Ruoli { get; set; }
        public virtual DbSet<Utente> Utenti { get; set; }
        public virtual DbSet<Funzione> Funzioni { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Download> Download { get; set; }
    }
}
