//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortaleFornitori.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utente
    {
        public int IdUser { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public Nullable<int> IdFornitore { get; set; }
        public int IdRuolo { get; set; }
    
        public virtual Fornitore Fornitore { get; set; }
        public virtual Ruolo Ruolo { get; set; }
    }
}
